models:
  - name: dim_listings_cleansed
    description: "Clean listing data with additional transformation"
    columns:
      - name: listing_id
        description: "Unique id for each listing"
        data_tests: 
          - not_null
          - unique

      - name: host_id
        description: "Unique identifier for the host of the listing"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: "Type of room available for booking"
        data_tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed__minimum_nights") }}'  #reference docs.md to describe description instead of call directly as "Minimum number of nights required for booking"
        data_tests:
          - positive_value #call and reference positive_value.sql

  - name: dim_listings_w_hosts
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 50
              max_value: 5000
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: WARN
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: NUMBER