models:
  - name: dim_listings_cleansed
    description: "Clean listing data with additional transformation"
    columns:
      - name: listing_id
        description: "Unique id for each listing"
        data_tests: 
          - not_null
          - unique

      - name: host_id
        description: "Unique identifier for the host of the listing"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: "Type of room available for booking"
        data_tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed__minimum_nights") }}'  #reference docs.md to describe description instead of call directly as "Minimum number of nights required for booking"
        data_tests:
          - positive_value #call and reference positive_value.sql