sources:
  - name: airbnb
    schema: raw
    tables: 
      - name: listings
        identifier: raw_listings
        columns:
           - name: room_type
             data_tests:
               - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
      - name: hosts
        identifier: raw_hosts
      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:  #use command : dbt source freshness, only use for monitoring pipeline run ontime or not as SLA(agreement between DA and DE), not interupt dbt run
          warn_after: { count: 1, period: hour}
          error_after: { count: 24, period: hour}

#if we need to use pipeline to check freshness --> need to write other freshness  in command line   
#dbt source freshness || exit 1
#dbt run